name: Hello World
on:
  push:
    paths:
      - 'Lab1/**'
jobs: 
  HelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create prog
        run: g++ hello.cpp
      - run: ./a.out
