name: Hello World
on: push
jobs: 
  HelloWorld:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running makefile"
      - name: create prog
        run: g++ hello.cpp
        uses: https://github.com/JunLin2001/CISC-3142-REPO/blob/main/hello.cpp
      - run: ./a.out
