name: Lab10
on:
  push:
    paths:
      - 'Lab10/**'
jobs: 
  Run1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o ex10 Excercise.cpp
      - run: ./ex10