name: Lab4
on:
  push:
    paths:
      - 'Lab4/**'
jobs: 
  Run1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o p2 Pratice2.cpp
      - run: ./p2
jobs2: 
  Run2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o p1 Pratice1.cpp
      - run: ./p1