name: Lab4
on:
  push:
    paths:
      - 'Lab4/**'
jobs: 
  RunLab4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: Lab4/
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o p2 Pratice2.cpp
      - run: ./p2