name: Lab4
on:
  push:
    paths:
      - 'Lab4/**'
jobs: 
  RunLab4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o ex3.17 Excercise3.17.cpp
      - run: ./ex3.17