name: Lab5
on:
  push:
    paths:
      - 'Lab5/**'
jobs: 
  Run1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create prog
        run: g++ -o sd SumofDigits.cpp
      - run: ./sd
  Run2:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o pr PrimeNumber.cpp
      - run: ./pr
  Run3:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o lin LinearRegression.cpp
      - run: ./lin