name: Lab5
on:
  push:
    paths:
      - 'Lab5/**'
jobs: 
  Run1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o sum SumofDigits.cpp
      - run: ./sum
  Run2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o prime PrimeNumber.cpp
      - run: ./prime
  Run3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o linear LinearRegression.cpp
      - run: ./linear