name: Lab7
on:
  push:
    paths:
      - 'Lab7/**'
jobs: 
  Run1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Running makefile"
      - name: create progs
        run: g++ -o rec Rectangle.cpp
      - run: ./rec